server:
  port: 9092
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wolfcode_shop_order
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
  dubbo:
    application:
      name: shop-order-server
    base-package: cn.wolfcode.shop
    protocol:
          port: 20882
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.wolfcode.shop.domain